version: '3'
services:
  app:
    build: ./packages/server
    depends_on:
      - postgres
      - ganache
    ports:
      - '3000'
    networks:
      - netwr
    volumes:
      - ./packages/server:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./packages/server/.env
    command: npm run test
  postgres:
    image: postgres
    ports:
      - '5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cle_si_vous_plait
      PGDATA: /data/postgres
      POSTGRES_DB: shreks-swamp
    networks:
      - netwr
    volumes:
      - './packages/server/postgres-data-e2e:/data/postgres'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 12s
      timeout: 5s
      retries: 5
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - '8545'
    volumes:
      - ./ganache_data:/ganache_data
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --deterministic
      - --db=/ganache_data
      - --mnemonic
      - 'minimum symptom minute gloom tragic situate silver mechanic salad amused elite beef'
      - --networkId
      - '5777'
      - --hostname
      - '0.0.0.0'
      - --debug
    networks:
      - netwr
networks:
  netwr: