version: '3'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - '9099:3000'
    networks:
      - netwr
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
  postgres:
    image: postgres
    ports:
      - '5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cle_si_vous_plait
      PGDATA: /data/postgres
      POSTGRES_DB: shreks-swamp
    networks:
      - netwr
    volumes:
      - './postgres-data:/data/postgres'
networks:
  netwr: